### PR TITLE
Update landing page

### PR DESCRIPTION
**Pull request by birkskyum**
@nyurik, @HarelM, I took the time to fix the docker scripts so we can now build and run this repo. I updated the landing page with correct links, a tiny post in the blog pointing to maplibre newsletter with more migration information etc.

The big difference in line count is because I removed the "releases" folder from here, because all of these assets are better hosted in the [Releases section of the Maputnik repo](https://github.com/maplibre/maputnik/releases).

### CODE REVIEW

**Comment by HarelM** [comment]
What are the plans for the releases? Not that I think they are really worth keeping, but just to understand what are their storage plans.

**Comment by birkskyum** [comment]
Storage plans? I think they were just copied into the repo as static assets, which can contain a lot of releases within the 2GB limit, and I don't see any signs of a CDN or CI configuration. It's not great to load `<script />` links directly from file trees in repo... Github recommends using GitHub releases for that type of asset distribution.

**Comment by HarelM** [comment]
Since they are deleted from here, my question is where will they be placed? And if they will be placed somewhere else?

**Comment by birkskyum** [comment]
They are in the assets section of each release here: https://github.com/maplibre/maputnik/releases/tag/v1.7.0

**Comment by HarelM** [comment]
Oh, OK, cool, thanks!

**Comment by birkskyum** [comment]
@nyurik, any idea who has access to this repo?

**Pull request merged**
